import test from'node:test';import assert from'node:assert/strict';import{infer,validate,tsType}from'../public/assets/schema-core.js';import{analyse,day}from'../public/assets/cohort-core.js';import{parseCSV}from'../public/assets/util.js';import{handle,encode,decode}from'../lib/commerce.mjs';
test('contract catches type changes, required fields and additional fields',()=>{const schema=infer({id:2,tags:['a'],owner:null});assert.deepEqual(validate({id:3,tags:[],owner:null},schema),[]);assert.equal(validate({id:'3',tags:[false],extra:true},schema).length,4);assert.match(tsType(schema),/"owner": null/)});
test('empty and mixed arrays, JSON special property names',()=>{const s=infer(JSON.parse('{"__proto__":1,"items":[1,"x",null],"empty":[]}'));assert.deepEqual(validate(JSON.parse('{"__proto__":1,"items":[null,2],"empty":[{}]}'),s),[]);assert.equal(validate({items:[false],empty:[]},s).length,2)});
test('CSV quoted comma, embedded newline and malformed input',()=>{assert.deepEqual(parseCSV('a,b\n"x,y","z\nq"'),[['a','b'],['x,y','z\nq']]);assert.throws(()=>parseCSV('a\n"oops'),/not closed/);assert.throws(()=>day('2026-02-30'),/Invalid date/)});
test('cohorts enforce maturity, inclusive return window and exclusions',()=>{const csv='order_id,customer_id,ordered_at,net_sales\n1,A,2026-01-01,100\n2,A,2026-01-31,70\n3,B,2026-02-01,90\n4,C,2026-03-01,90\n4,C,2026-03-01,90\n5,D,2026-04-01,100';const r=analyse(csv,'2026-03-02',30);assert.equal(r.eligible,1);assert.equal(r.returners,1);assert.equal(r.secondSales,70);assert.equal(r.held,2);assert.equal(r.future,1);assert.equal(r.duplicates,1);assert.equal(r.cohorts.at(-1).rate,null)});
process.env.CART_SIGNING_KEY='local-test-key-that-is-never-used-in-production';
test('cart signatures reject tampering and expiry',()=>{const t=encode({lines:[{id:'daypack-forest',quantity:2}]});assert.equal(decode(t).lines[0].quantity,2);assert.deepEqual(decode(t+'x'),{})});
test('server cart persists, validates quantity and owns pricing',async()=>{let cookie='';async function call(body){const r=await handle(new Request('https://example.test/api/commerce/cart',{method:body===undefined?'GET':'POST',headers:{cookie,'Content-Type':'application/json',origin:'https://example.test'},...(body===undefined?{}:{body:JSON.stringify(body)})}));if(r.headers.get('set-cookie'))cookie=r.headers.get('set-cookie').split(';')[0];return{status:r.status,body:await r.json()}}assert.equal((await call()).body.quantity,0);let r=await call({action:'add',variantId:'daypack-forest',quantity:2,price:1});assert.equal(r.body.total,1780000);assert.equal((await call()).body.quantity,2);assert.equal((await call({action:'add',variantId:'daypack-forest',quantity:4})).status,422);assert.equal((await call({action:'add',variantId:'daypack-ink',quantity:1})).status,422);assert.equal((await call({action:'add',variantId:'daypack-forest',quantity:1.5})).status,400);assert.equal((await call(null)).status,400);r=await call({action:'update',lineId:'daypack-forest',quantity:1});assert.equal(r.body.total,890000);assert.equal((await call({action:'remove',lineId:'daypack-forest'})).body.quantity,0);const denied=await handle(new Request('https://example.test/api/commerce/cart',{method:'POST',headers:{origin:'https://elsewhere.test','Content-Type':'application/json'},body:'{}'}));assert.equal(denied.status,403)});

test('carry sets commit all items together and reject the whole set if one item fails',async()=>{
 const call=async(items,cookie='')=>{const r=await handle(new Request('https://example.test/api/commerce/cart',{method:'POST',headers:{'content-type':'application/json',cookie},body:JSON.stringify({action:'add-set',items})}));return {r,body:await r.json()}};
 let {r,body}=await call([{variantId:'daypack-clay',quantity:1},{variantId:'pouch',quantity:1},{variantId:'bottle',quantity:1}]);assert.equal(body.total,1210000);assert.equal(body.quantity,3);
 const cookie=r.headers.get('set-cookie').split(';')[0];({r}=await call([{variantId:'pouch',quantity:1},{variantId:'daypack-ink',quantity:1}],cookie));assert.equal(r.status,422);assert.equal(r.headers.get('set-cookie'),null);
 const persisted=await handle(new Request('https://example.test/api/commerce/cart',{headers:{cookie}}));assert.equal((await persisted.json()).quantity,3);
});
