import{createHmac,timingSafeEqual}from'node:crypto';
export const catalog=[
 {handle:'canvas-daypack',title:'The daypack',subtitle:'Canvas / leather',description:'A rolltop shape with room for the everyday carry. Choose forest green or clay, then build your set with the matching pouch and bottle.',image:'/assets/forest.png',variants:[{id:'daypack-forest',title:'Forest',price:890000,currency:'INR',available:true,limit:5,image:'/assets/forest.png'},{id:'daypack-clay',title:'Clay',price:890000,currency:'INR',available:true,limit:5,image:'/assets/clay.png'},{id:'daypack-ink',title:'Ink',price:890000,currency:'INR',available:false,limit:0}]},
 {handle:'canvas-pouch',title:'The small-things pouch',subtitle:'For cables, keys and loose ends',description:'A canvas zip pouch for the things that otherwise settle at the bottom of your bag.',image:'/assets/pouch.png',variants:[{id:'pouch',title:'Natural canvas',price:140000,currency:'INR',available:true,limit:5}]},
 {handle:'everyday-bottle',title:'The everyday bottle',subtitle:'A place in your everyday carry',description:'A simple bottle to complete the carry set.',image:'/assets/bottle.png',variants:[{id:'bottle',title:'Olive',price:180000,currency:'INR',available:true,limit:5}]}
];
const json=(body,status=200,headers={})=>Response.json(body,{status,headers:{'Cache-Control':'no-store','X-Content-Type-Options':'nosniff',...headers}});
function key(){const k=process.env.CART_SIGNING_KEY;if(!k||k.length<32)throw Error('Cart storage is not configured.');return k}
export function encode(state){const data=Buffer.from(JSON.stringify({...state,expires:Date.now()+7*86400000})).toString('base64url');return data+'.'+createHmac('sha256',key()).update(data).digest('base64url')}
export function decode(token){try{const[data,signature]=token.split('.');const expected=createHmac('sha256',key()).update(data).digest();const actual=Buffer.from(signature,'base64url');if(actual.length!==expected.length||!timingSafeEqual(actual,expected))return{};const state=JSON.parse(Buffer.from(data,'base64url').toString());return state.expires>Date.now()?state:{}}catch{return{}}}
const cookie=(req,state)=>'fw_cart='+encode(state)+'; Path=/; HttpOnly; SameSite=Lax; Max-Age=604800'+(new URL(req.url).protocol==='https:'?'; Secure':'');
function read(req){const token=req.headers.get('cookie')?.split(';').map(v=>v.trim()).find(v=>v.startsWith('fw_cart='))?.slice(8);return token?decode(token):{}}
export function localCart(state={}){const lines=(state.lines||[]).flatMap(line=>{for(const p of catalog){const v=p.variants.find(v=>v.id===line.id);if(v&&v.available&&Number.isInteger(line.quantity)&&line.quantity>0&&line.quantity<=v.limit)return[{id:v.id,variantId:v.id,handle:p.handle,title:p.title,variant:v.title,price:v.price,quantity:line.quantity,image:v.image||p.image,total:v.price*line.quantity,currency:v.currency}]}return[]});return{lines,total:lines.reduce((s,l)=>s+l.total,0),quantity:lines.reduce((s,l)=>s+l.quantity,0),currency:'INR',checkoutUrl:null,source:'independent-catalogue'}}
const fields=`id checkoutUrl totalQuantity cost { subtotalAmount { amount currencyCode } } lines(first:50) { nodes { id quantity merchandise { ... on ProductVariant { id title price { amount currencyCode } image { url } product { title handle featuredImage { url } } } } } }`;
const domain=()=>{const d=process.env.SHOPIFY_STORE_DOMAIN||'';if(d&&!/^[a-z0-9][a-z0-9-]*\.myshopify\.com$/i.test(d))throw Error('Shopify store domain is invalid.');return d};
async function shop(query,variables,req){const headers={'Content-Type':'application/json'};if(process.env.SHOPIFY_STOREFRONT_TOKEN)headers['Shopify-Storefront-Private-Token']=process.env.SHOPIFY_STOREFRONT_TOKEN;const ip=req.headers.get('x-nf-client-connection-ip');if(ip)headers['Shopify-Storefront-Buyer-IP']=ip;const r=await fetch('https://'+domain()+'/api/2026-07/graphql.json',{method:'POST',headers,body:JSON.stringify({query,variables}),signal:AbortSignal.timeout(15000)});if(!r.ok)throw Error('Shopify returned '+r.status+'. Please try again after checking the cart.');const d=await r.json();if(d.errors?.length)throw Error(d.errors[0].message);return d.data}
function remoteCart(c){if(!c)return{lines:[],quantity:0,total:0,currency:'INR',checkoutUrl:null,source:'shopify'};return{lines:c.lines.nodes.map(l=>({id:l.id,variantId:l.merchandise.id,title:l.merchandise.product.title,handle:l.merchandise.product.handle,variant:l.merchandise.title,price:Math.round(Number(l.merchandise.price.amount)*100),currency:l.merchandise.price.currencyCode,total:Math.round(Number(l.merchandise.price.amount)*100)*l.quantity,quantity:l.quantity,image:l.merchandise.image?.url||l.merchandise.product.featuredImage?.url})),quantity:c.totalQuantity,total:Math.round(Number(c.cost.subtotalAmount.amount)*100),currency:c.cost.subtotalAmount.currencyCode,checkoutUrl:c.checkoutUrl,source:'shopify'}}
export async function handle(req){const path=new URL(req.url).pathname;try{if(req.method!=='GET'&&req.method!=='POST')return json({error:'Method not allowed.'},405,{Allow:'GET, POST'});if(req.method==='POST'){const origin=req.headers.get('origin');if(origin&&origin!==new URL(req.url).origin)return json({error:'Cross-origin writes are not allowed.'},403)}const connected=!!domain();if(path==='/api/commerce/status'&&req.method==='GET')return json({service:'FIELDWORK commerce',catalogue:connected?'Shopify':'Independent collection',shopifyConnected:connected,checkout:connected?'Shopify checkout':'Store connection pending',routes:['GET /api/commerce/products','GET /api/commerce/cart','POST /api/commerce/cart'],version:'1.0.0'});if(path==='/api/commerce/products'&&req.method==='GET'){if(!connected)return json({products:catalog,source:'independent-catalogue'});const d=await shop(`query { products(first:30) { nodes { handle title description featuredImage { url } variants(first:20) { nodes { id title availableForSale price { amount currencyCode } image { url } } } } } }`,{},req);return json({source:'shopify',products:d.products.nodes.map(p=>({handle:p.handle,title:p.title,subtitle:'',description:p.description,image:p.featuredImage?.url,variants:p.variants.nodes.map(v=>({id:v.id,title:v.title,available:v.availableForSale,price:Math.round(Number(v.price.amount)*100),currency:v.price.currencyCode,image:v.image?.url,limit:5}))}))});}if(path!=='/api/commerce/cart')return json({error:'Route not found.'},404);key();const state=read(req);if(req.method==='GET'){if(!connected)return json(localCart(state));if(!state.shopifyCartId)return json(remoteCart(null));const d=await shop(`query($id:ID!){cart(id:$id){${fields}}}`,{id:state.shopifyCartId},req);return json(remoteCart(d.cart))}if(!req.headers.get('content-type')?.includes('application/json'))return json({error:'Use application/json.'},415);const text=await req.text();if(text.length>4096)return json({error:'Request is too large.'},413);let body;try{body=JSON.parse(text)}catch{return json({error:'Invalid JSON.'},400)}if(!body||Array.isArray(body)||typeof body!=="object")return json({error:"Use a JSON object."},400);const{action,variantId,lineId,quantity}=body;if(!['add','add-set','update','remove','clear'].includes(action))return json({error:'Choose add, update, remove or clear.'},400);if(['add','update'].includes(action)&&(!Number.isInteger(quantity)||quantity<1||quantity>5))return json({error:'Quantity must be a whole number from 1 to 5.'},400);if(action==='add-set'){
 if(connected)return json({error:'Use the product page to add items from the connected store.'},409);
 if(!Array.isArray(body.items)||body.items.length<1||body.items.length>3)return json({error:'Choose one to three items.'},400);
 const lines=localCart(state).lines.map(l=>({id:l.id,quantity:l.quantity}));
 for(const item of body.items){
  if(!item||!Number.isInteger(item.quantity)||item.quantity<1||item.quantity>5)return json({error:'Choose a whole quantity from 1 to 5.'},400);
  const v=catalog.flatMap(p=>p.variants).find(v=>v.id===item.variantId);
  if(!v||!v.available)return json({error:'One of the selected items is unavailable.'},422);
  const existing=lines.find(l=>l.id===v.id);const quantity=(existing?.quantity||0)+item.quantity;
  if(quantity>v.limit)return json({error:'The maximum is '+v.limit+' per item. Review your bag.'},422);
  if(existing)existing.quantity=quantity;else lines.push({id:v.id,quantity});
 }
 const next={lines};return json(localCart(next),200,{'Set-Cookie':cookie(req,next)});
}if(connected){let result;if(action==='clear')return json(remoteCart(null),200,{'Set-Cookie':cookie(req,{})});if(!state.shopifyCartId){if(action!=='add')return json({error:'The cart has expired. Add the product again.'},409);const d=await shop(`mutation($input:CartInput!){cartCreate(input:$input){cart{${fields}} userErrors{message}}}`,{input:{lines:[{merchandiseId:variantId,quantity}]}},req);result=d.cartCreate}else{const name=action==='add'?'cartLinesAdd':action==='update'?'cartLinesUpdate':'cartLinesRemove';const variable=action==='add'?'[CartLineInput!]!':action==='update'?'[CartLineUpdateInput!]!':'[ID!]!';const arg=action==='remove'?'lineIds':'lines';const lines=action==='add'?[{merchandiseId:variantId,quantity}]:action==='update'?[{id:lineId,quantity}]:[lineId];const d=await shop(`mutation($id:ID!,$lines:${variable}){${name}(cartId:$id,${arg}:$lines){cart{${fields}} userErrors{message}}}`,{id:state.shopifyCartId,lines},req);result=d[name]}if(result.userErrors?.length)return json({error:result.userErrors[0].message},422);if(!result.cart)return json({error:'Shopify did not return a cart. Review it before trying again.'},502);return json(remoteCart(result.cart),200,{'Set-Cookie':cookie(req,{shopifyCartId:result.cart.id})})}const current=localCart(state);let lines=current.lines.map(l=>({id:l.id,quantity:l.quantity}));if(action==='clear')lines=[];else if(action==='remove')lines=lines.filter(l=>l.id!==lineId);else{const id=action==='add'?variantId:lineId;const v=catalog.flatMap(p=>p.variants).find(v=>v.id===id);if(!v)return json({error:'Unknown product variant.'},404);if(!v.available)return json({error:'This variant is unavailable. Choose another option.'},422);const line=lines.find(l=>l.id===id),total=action==='add'?(line?.quantity||0)+quantity:quantity;if(total>v.limit)return json({error:'The maximum is '+v.limit+' per variant.'},422);if(action==='update'&&!line)return json({error:'That item is no longer in your bag.'},409);if(line)line.quantity=total;else lines.push({id,quantity:total})}const next={lines};return json(localCart(next),200,{'Set-Cookie':cookie(req,next)})}catch(e){return json({error:e.name==='TimeoutError'?'The provider response timed out. Refresh your bag before trying again.':e.message||'The request could not complete.'},503)}}
